# Site settings
title: inuitcss
email: csswizardry@gmail.com
description: >
  Extensible, scalable, Sass-based, OOCSS framework for large and long-lasting
  UI projects.
baseurl: ""
url: "http://inuitcss.com"

# Project info
github: "https://github.com/inuitcss/inuitcss"
version: 6.0.0-beta.5
commit: d84cb4762c945714f4440af6a3db48bce85a4cf6

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  about:
    output: true
    permalink: /:collection/:path/
  docs:
    output: true
    permalink: /:collection/:path/
  demo:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: page
