# Site settings
title: inuitcss
email: csswizardry@gmail.com
description: >
  Extensible, scalable, Sass-based, OOCSS framework for large and long-lasting
  UI projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://inuitcss.com" # the base hostname & protocol for your site

# Project info
github: "https://github.com/inuitcss/inuitcss"
version: 6.0.0-beta.4
commit: 126bebe2ff2146b7101ef28fb1b2c0c4832261dc

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/
  demo:
    output: true
    permalink: /:collection/:path/
